### PR TITLE
fix nil jobs returned from api

### PR DESCRIPTION
**Pull request by BradHudson**
````
[3] pry(Cb::Clients::Recommendation)> json_hash
=> {"Results"=>{"JobRecommendation"=>{"Jobs"=>nil}}}
[4] pry(Cb::Clients::Recommendation)> json_hash.fetch('Results', {}).fetch('JobRecommendation', {}).fetch('Jobs', {}).fetch('CompanyJob', []).each
NoMethodError: undefined method `fetch' for nil:NilClass
from (pry):4:in `for_company'
````

### CODE REVIEW

**Comment by usbsnowcrash** [comment]
Was this a good idea to merge?  Why does the API return nil jobs?  Shouldn't we throw an error like we do in other APIs when we dont get the expected model back?  Now instead of using error handling I have to check for blank jobs every time?

**Comment by Casao** [comment]
Why are we using Exceptions to indicate no results? That's not an exception. That's a perfectly valid state.

**Comment by usbsnowcrash** [comment]
Null jobs are not the same as no results

**Comment by Casao** [comment]
This is supposedly to be an array of jobs, and it's coming back nil. Sounds like no results, and not an empty job.

**Comment by Casao** [comment]
If not, this is just a really, really ugly API structure. So I guess that's possible too.

**Comment by ausmith** [comment]
So the API results that we are seeing, and is causing this looks like

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Results>
    <JobRecommendation>
        <Jobs />
    </JobRecommendation>
</Results>
```

And we are erroring on `Jobs` being empty. Shouldn't we handle that case @usbsnowcrash?

**Comment by BradHudson** [comment]
I was under the impression empty jobs was a valid thing to return, but we can rework it if we want.

**Pull request merged**
