### PR TITLE
Dynamic screener as internal apply

### PR DESCRIPTION
**Pull request by derrickwilliams**
Adding `is_dynamic_screener` field from application form API response. This field is used in consumer-main apply_controller for including dynamic screener jobs as internal apply.

### CODE REVIEW

**Comment by Casao** [comment]
We just published a 2.3.1, you'll need to bump API version again

**Comment by bowersaa** [comment]
Merge conflicts.

**Comment by usbsnowcrash** [comment]
Need to add a line to CHANGELOG as well describing what is new in this version

**Comment by mmoldavan** [comment]
added a changelog

**Comment by derrickwilliams** [comment]
What should we do to make Travis happy?

**Comment by tkling** [comment]
Looks like Travis is failing due to this: `Gem::InstallError: nokogiri requires Ruby version >= 2.1.0.`

It's only breaking for ruby < 2.1, so I think maybe we could drop support for 2.1 and be ok. @Casao @bowersaa @usbsnowcrash what do you think?

**Comment by tkling** [comment]
@derrickwilliams Hey hey, merge updated master into this branch and your Travis woes will be no more :thumbsup:

**Comment by derrickwilliams** [comment]
Thanks @tkling.

**Pull request merged**
